#!/bin/bash

mime=$(file -Lbs --mime-type "$1")
category=${mime%%/*}
kind=${mime##*/}
ext=${1##*.}
if [ "$kind" = json ]; then
  jq -Cr . "$1"
elif [ -d "$1" ]; then
  eza -hl --git --color=always --icons "$1"
elif [ "$kind" = pdf ]; then
  pdftotext -q "$1" - | sed "s/\f/$(hr ─)\n/g"
elif [ "$kind" = rfc822 ]; then
  bat --color=always -lEmail "$1"
elif [ "$kind" = javascript ]; then
  bat --color=always -ljs "$1"
elif [ "$category" = image ]; then
  chafa -f symbols -s 50x50 "$1"
elif [ "$category" = text ]; then
  bat --color=always "$1"
else
  bat --color=alawys "$1"
fi
