#!/usr/bin/env lua

local function script_dir()
	local src = debug.getinfo(1, "S").source
	if src:sub(1, 1) == "@" then
		src = src:sub(2)
	end
	return (src:match("(.*/)")) or "./"
end

local dir = script_dir()
package.path = package.path .. ";" .. dir .. "?.lua" .. ";" .. dir .. "?/init.lua"

-- Load the sketchybar-package and prepare the helper binaries
require("helpers")
require("init")
