[tools]
java = "latest"
node = "24"
lua = "5.1"
pnpm = "latest"
npm = "latest"
maven = "latest"
gradle = "latest"
kotlin = "latest"
rust = "latest"
"npm:wrangler" = "latest"
"npm:typescript-language-server" = "latest"
"npm:typescript" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:pyright" = "latest"
"pipx:jcodemunch-mcp" = "latest"
[settings]
idiomatic_version_file_enable_tools = ["node"]
